version: '3'

networks:
  xhslink-proxy:
    name: proxy_network
    external: true

services: 
  xhs-link:
    container_name: xhs-link
    build:
      context: .
    image: xhs-link:latest
    restart: unless-stopped
    networks: 
      - xhslink-proxy
    volumes:
      - ./index.html:/app/index.html
    environment:
      PROXY_HOST: ""
      PROXY_PORT: ""
      PROXY_USERNAME: ""
      PROXY_PASSWORD: ""
      HOST: "0.0.0.0"
      PORT: "5000"
    ports:
      - 127.0.0.1:5000:5000

